platform :ios, '11.0'
inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'


# Flutter
flutter_application_path = '../flutter_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterIos' do
  pod 'SnapKit'
  # 引入flutter
  install_all_flutter_pods(flutter_application_path)
  
  # Flutter相关集成是不支持bitcode的，
  #所以需要将相关产物的bitcode功能关闭。
  #如果你的现有工程中仓库众多，有的仓库是必须bitcode的，
  #这样的话就需要每次pod install之后再在工程配置中手动设置回来，
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name =="App" || target.name =="Flutter"
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] ='NO'
      end
    end
  end
end
  
end


