platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'


target 'QYInterview' do
  pod 'SDWebImage', '~> 5.10.2'
  pod 'SnapKit'
  pod 'Toaster'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'SDMagicHook'
  pod 'PandaHook'
  pod 'Aspects'
  pod 'EasySwiftHook'
  pod 'HandyJSON'
end
